/* create tables */
CREATE TABLE WAREHOUSE.EMPLOYEE (
  /* variables */
  FNAME VARCHAR(15) NOT NULL,
  MINIT CHAR, 
  LNAME VARCHAR(15) NOT NULL,
  SSN CHAR(9) NOT NULL,
  BDATE DATE,
  ADDRESS VARCHAR(30),
  SEX CHAR,
  SALARY DECIMAL(10, 2),
  SUPER_SSN CHAR(9), 
  DUO INT NOT NULL,

  /* constraints */
  PRIMARY KEY (SSN)
  );

-- foreign keys can't be added until table we are referencing has been created
ALTER TABLE WAREHOUSE.EMPLOYEE ADD FOREIGN KEY (SUPER_SSN) REFERENCES WAREHOUSE.EMPLOYEE(SSN);

CREATE TABLE WAREHOUSE.DEPARTMENT (
  /* variables */
  DNAME VARCHAR(15) NOT NULL,
  DNUMBER INT NOT NULL,
  MGR_SSN CHAR(9) NOT NULL,
  MGR_START_DATE DATE,

  /* constraints */
  PRIMARY KEY (DNUMBER),
  UNIQUE (DNAME),
  FOREIGN KEY (MGR_SSN) REFERENCES EMPLOYEE(SSN)
  );

-- foreign keys can't be added until table we are referencing has been created
ALTER TABLE WAREHOUSE.EMPLOYEE ADD FOREIGN KEY (DUO) REFERENCES WAREHOUSE.DEPARTMENT(DNUMBER);

CREATE TABLE WAREHOUSE.DEPT_LOCATIONS (
  /* variables */
  DNUMBER INT NOT NULL,
  DLOCATION VARCHAR(15) NOT NULL,

  /* constraints */
  PRIMARY KEY (DNUMBER, DLOCATION),
  FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
  );

CREATE TABLE WAREHOUSE.PROJECT (
  /* variables */
  PNAME VARCHAR(15) NOT NULL,
  PNUMBER INT NOT NULL,
  PLOCATION VARCHAR(15),
  DNUM INT NOT NULL,

  /* constraints */
  PRIMARY KEY (PNUMBER),
  UNIQUE (PNAME),
  FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER) 
  );

CREATE TABLE WAREHOUSE.WORKS_ON (
  /* variables */
  ESSN CHAR(9) NOT NULL,
  PNO INT NOT NULL,
  HOURS DECIMAL(3, 1) NOT NULL,

  /* constraints */
  PRIMARY KEY (ESSN, PNO),
  FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
  FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER) 
  ); 

CREATE TABLE WAREHOUSE.DEPENDENT (
  /* variables */
  ESSN CHAR(9) NOT NULL,
  DEPENDENT_NAME VARCHAR(15) NOT NULL,
  SEX CHAR,
  BDATE DATE,
  RELATIONSHIP VARCHAR(8),

  /* constraints */
  PRIMARY KEY (ESSN, DEPENDENT_NAME),
  FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN) 
  );